### ISSUE TITLE
sao mina my-app 报错

### ISSUE THREAD

**Issue by strange-fish** [tinajs/tina#17]
使用sao 0.22.17可以正常安装， 但sao目前的版本1.2.0会报错。

```
npm ERR! 404 Not Found: sao-mina@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tmg2017/.npm/_logs/2018-11-13T08_33_20_683Z-debug.log
/usr/local/lib/node_modules/sao/lib/installPackages.js:89
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

Error: Failed to install sao-mina@latest in /Users/tmg2017/.sao/V1/packages/4bbaad60
    at ChildProcess.ps.on.code (/usr/local/lib/node_modules/sao/lib/installPackages.js:89:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
```

**Comment by callmesoul** [comment]
还没好么？

**Comment by imyelo** [comment]
[sao-mina@2.0.3](https://github.com/tinajs/template-mina/releases/tag/v2.0.3) 和 [sao-tina@2.0.2](https://github.com/tinajs/template-tina/releases/tag/v2.0.2) 已支持 sao@1.x
